---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-agent.metrics.service.name" }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: grafana-agent
spec:
  clusterIP: None
  ports:
  - name: grafana-agent-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: grafana-agent
