---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grafana-agent.metrics.serviceAccount.name" }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grafana-agent.logs.serviceAccount.name" }}
  namespace: {{ .Release.Namespace }}
